apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpp-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpp-api
  minReplicas: 2
  maxReplicas: 8              # scales up to 8 pods under high load
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70   # scale up when CPU > 70%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
